// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {hardware} from '../models';

export function CancelModelOperation():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteModel(arg1:string,arg2:string):Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetHardwareProfile():Promise<hardware.Profile>;

export function GetPreferences():Promise<main.Preferences>;

export function InstallOllamaModel(arg1:string):Promise<void>;

export function InstallWhisperModel(arg1:string):Promise<void>;

export function ListMeetingHistory():Promise<Array<main.MeetingHistoryItem>>;

export function ListModelCatalog():Promise<Array<main.ModelCatalogItem>>;

export function ListOllamaModels():Promise<Array<main.ModelOption>>;

export function ListWhisperModels():Promise<Array<main.ModelOption>>;

export function OpenFileDialog():Promise<string>;

export function OpenHistoryReport(arg1:string):Promise<void>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function SavePreferences(arg1:main.Preferences):Promise<void>;
