// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelModelOperation() {
  return window['go']['main']['AppService']['CancelModelOperation']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['AppService']['CopyToClipboard'](arg1);
}

export function DeleteModel(arg1, arg2) {
  return window['go']['main']['AppService']['DeleteModel'](arg1, arg2);
}

export function GetAppInfo() {
  return window['go']['main']['AppService']['GetAppInfo']();
}

export function GetHardwareProfile() {
  return window['go']['main']['AppService']['GetHardwareProfile']();
}

export function GetPreferences() {
  return window['go']['main']['AppService']['GetPreferences']();
}

export function InstallOllamaModel(arg1) {
  return window['go']['main']['AppService']['InstallOllamaModel'](arg1);
}

export function InstallWhisperModel(arg1) {
  return window['go']['main']['AppService']['InstallWhisperModel'](arg1);
}

export function ListMeetingHistory() {
  return window['go']['main']['AppService']['ListMeetingHistory']();
}

export function ListModelCatalog() {
  return window['go']['main']['AppService']['ListModelCatalog']();
}

export function ListOllamaModels() {
  return window['go']['main']['AppService']['ListOllamaModels']();
}

export function ListWhisperModels() {
  return window['go']['main']['AppService']['ListWhisperModels']();
}

export function OpenFileDialog() {
  return window['go']['main']['AppService']['OpenFileDialog']();
}

export function OpenHistoryReport(arg1) {
  return window['go']['main']['AppService']['OpenHistoryReport'](arg1);
}

export function OpenOutputFolder(arg1) {
  return window['go']['main']['AppService']['OpenOutputFolder'](arg1);
}

export function SavePreferences(arg1) {
  return window['go']['main']['AppService']['SavePreferences'](arg1);
}
