// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPipeline():Promise<void>;

export function ImportAudioFile(arg1:string):Promise<void>;

export function IsRunning():Promise<boolean>;

export function RetrySummary():Promise<void>;

export function RunPipeline(arg1:string):Promise<void>;
