// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPipeline() {
  return window['go']['main']['PipelineService']['CancelPipeline']();
}

export function ImportAudioFile(arg1) {
  return window['go']['main']['PipelineService']['ImportAudioFile'](arg1);
}

export function IsRunning() {
  return window['go']['main']['PipelineService']['IsRunning']();
}

export function RetrySummary() {
  return window['go']['main']['PipelineService']['RetrySummary']();
}

export function RunPipeline(arg1) {
  return window['go']['main']['PipelineService']['RunPipeline'](arg1);
}
