// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetElapsed() {
  return window['go']['main']['RecordService']['GetElapsed']();
}

export function IsRecording() {
  return window['go']['main']['RecordService']['IsRecording']();
}

export function PauseRecording() {
  return window['go']['main']['RecordService']['PauseRecording']();
}

export function ResumeRecording() {
  return window['go']['main']['RecordService']['ResumeRecording']();
}

export function StartRecording(arg1, arg2) {
  return window['go']['main']['RecordService']['StartRecording'](arg1, arg2);
}

export function StopRecording() {
  return window['go']['main']['RecordService']['StopRecording']();
}
