// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetElapsed():Promise<number>;

export function IsRecording():Promise<boolean>;

export function PauseRecording():Promise<void>;

export function ResumeRecording():Promise<void>;

export function StartRecording(arg1:string,arg2:string):Promise<void>;

export function StopRecording():Promise<string>;
